apiVersion: v1
kind: ConfigMap
metadata:
  name: tradeflow-config
  namespace: {{ .Values.global.namespace }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/{{ .Values.postgres.database }}"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  ORDER_SERVICE_URL: "http://order-service:{{ .Values.orderService.port }}"