apiVersion: v1
kind: Secret
metadata:
  name: tradeflow-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username | quote }}
  JWT_SECRET: {{ .Values.orderService.jwt.secret | quote }}
  JWT_EXPIRATION: {{ .Values.orderService.jwt.expiration | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.orderService.jwt.refreshExpiration | quote }}