# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/tradeflow
spring.datasource.username=tradeflow
spring.datasource.password=tradeflow123
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# JWT
jwt.secret=TradeFlowSuperSecretKeyForJWTSigningMustBe256BitsLongAtLeast
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.kafka.enabled=true
management.info.env.enabled=true

# Info
info.app.name=TradeFlow Order Service
info.app.version=1.0.0
info.app.description=B2B Purchase Order Platform

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.orderEventPublisher.sliding-window-size=10
resilience4j.circuitbreaker.instances.orderEventPublisher.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderEventPublisher.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderEventPublisher.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.orderEventPublisher.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.orderEventPublisher.register-health-indicator=true

# Resilience4j Retry
resilience4j.retry.instances.orderEventPublisher.max-attempts=3
resilience4j.retry.instances.orderEventPublisher.wait-duration=500ms

# Actuator ? expor circuit breaker
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true