apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradeflow

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - order-service.yaml
  - financial-service.yaml
  - frontend.yaml